name: pop_network
description: The plug-in built to simplify HTTP requests and help the developer to make good use of the Rest API's.
version: 1.1.0
homepage: https://github.com/PopcodeMobile/popnetwork
repository: https://github.com/PopcodeMobile/popnetwork

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dio: ^5.7.0
  http_mock_adapter: ^0.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
