name: popnetwork
description: The plug-in built to simplify HTTP requests and help the developer to make good use of the Rest API's.
version: 1.0.0
homepage: https://github.com/PopcodeMobile/popnetwork
repository: https://github.com/PopcodeMobile/popnetwork

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  dio: 5.0.3
  http_mock_adapter: ^0.4.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
